In [71]:
import cv2
import pandas
import tensorflow
import numpy
import torchvision
import torchvision.transforms as transforms
import torch
import numpy as np
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import random
from matplotlib import pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import keras


In [72]:
image_name_iterator = 0;
image_tensors = [];
real_labels = pandas.DataFrame();
row_index = 0;

In [73]:
def row_to_tensor(row):
    pixels = np.array([]);
    for i in row:
        pixels = np.append(pixels, i);
    image_tensors.append(torch.tensor(pixels));
    return row;
def normalization(df):
    df_min_max_scaled = df.copy() 
  
    for column in df_min_max_scaled.columns: 
        df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())     
    
    return df_min_max_scaled;





In [74]:
data = pandas.read_csv("train.csv");

#data = data.head();

display(data);

#data = data.head();
labels = pandas.DataFrame();
labels['l'] = data['label'];
data.drop(columns=['label'], inplace=True);

for i in range(10):
    real_labels.insert(i, str(i), np.zeros(42000));




display(labels);

#display(data);
#data = data.apply(row_to_tensor, axis=1);
#print(image_tensors);
#plt.show();

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

l
0      1
1      0
2      1
3      4
4      0
...   ..
41995  0
41996  1
41997  7
41998  6
41999  9

[42000 rows x 1 columns]

In [75]:
display(labels);

l
0      1
1      0
2      1
3      4
4      0
...   ..
41995  0
41996  1
41997  7
41998  6
41999  9

[42000 rows x 1 columns]

In [76]:
it = 0;

real_labels['0'] = labels['l'].apply(lambda x: 1 if x == 0 else 0);
real_labels['1'] = labels['l'].apply(lambda x: 1 if x == 1 else 0);
real_labels['2'] = labels['l'].apply(lambda x: 1 if x == 2 else 0);
real_labels['3'] = labels['l'].apply(lambda x: 1 if x == 3 else 0);
real_labels['4'] = labels['l'].apply(lambda x: 1 if x == 4 else 0);
real_labels['5'] = labels['l'].apply(lambda x: 1 if x == 5 else 0);
real_labels['6'] = labels['l'].apply(lambda x: 1 if x == 6 else 0);
real_labels['7'] = labels['l'].apply(lambda x: 1 if x == 7 else 0);
real_labels['8'] = labels['l'].apply(lambda x: 1 if x == 8 else 0);
real_labels['9'] = labels['l'].apply(lambda x: 1 if x == 9 else 0);

display(real_labels);

0  1  2  3  4  5  6  7  8  9
0      0  1  0  0  0  0  0  0  0  0
1      1  0  0  0  0  0  0  0  0  0
2      0  1  0  0  0  0  0  0  0  0
3      0  0  0  0  1  0  0  0  0  0
4      1  0  0  0  0  0  0  0  0  0
...   .. .. .. .. .. .. .. .. .. ..
41995  1  0  0  0  0  0  0  0  0  0
41996  0  1  0  0  0  0  0  0  0  0
41997  0  0  0  0  0  0  0  1  0  0
41998  0  0  0  0  0  0  1  0  0  0
41999  0  0  0  0  0  0  0  0  0  1

[42000 rows x 10 columns]

In [77]:
np.random.seed(0)
random.seed(0)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
torch.manual_seed(0)


In [78]:
device = torch.device("mps")
print(device)

mps


In [79]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()


In [80]:
real_labels_2 = pandas.DataFrame();
labels_2 = pandas.DataFrame();
labels_2['l'] = y_train;

real_labels_2['0'] = labels_2['l'].apply(lambda x: 1 if x == 0 else 0);
real_labels_2['1'] = labels_2['l'].apply(lambda x: 1 if x == 1 else 0);
real_labels_2['2'] = labels_2['l'].apply(lambda x: 1 if x == 2 else 0);
real_labels_2['3'] = labels_2['l'].apply(lambda x: 1 if x == 3 else 0);
real_labels_2['4'] = labels_2['l'].apply(lambda x: 1 if x == 4 else 0);
real_labels_2['5'] = labels_2['l'].apply(lambda x: 1 if x == 5 else 0);
real_labels_2['6'] = labels_2['l'].apply(lambda x: 1 if x == 6 else 0);
real_labels_2['7'] = labels_2['l'].apply(lambda x: 1 if x == 7 else 0);
real_labels_2['8'] = labels_2['l'].apply(lambda x: 1 if x == 8 else 0);
real_labels_2['9'] = labels_2['l'].apply(lambda x: 1 if x == 9 else 0);

In [81]:
display(labels_2);
display(real_labels_2);

l
0      5
1      0
2      4
3      1
4      9
...   ..
59995  8
59996  3
59997  5
59998  6
59999  8

[60000 rows x 1 columns]

0  1  2  3  4  5  6  7  8  9
0      0  0  0  0  0  1  0  0  0  0
1      1  0  0  0  0  0  0  0  0  0
2      0  0  0  0  1  0  0  0  0  0
3      0  1  0  0  0  0  0  0  0  0
4      0  0  0  0  0  0  0  0  0  1
...   .. .. .. .. .. .. .. .. .. ..
59995  0  0  0  0  0  0  0  0  1  0
59996  0  0  0  1  0  0  0  0  0  0
59997  0  0  0  0  0  1  0  0  0  0
59998  0  0  0  0  0  0  1  0  0  0
59999  0  0  0  0  0  0  0  0  1  0

[60000 rows x 10 columns]

In [82]:


device = torch.device("mps")
print(device)

# load the dataset, split into input (X) and output (y) variables
dataset = data;


X = data.to_numpy();
y = real_labels.to_numpy();
print(X);
y = np.append(y, real_labels_2.to_numpy());

for it in range(len(x_train)):
    if(it % 100 == 0): print((it / 60000) * 100);
    listt = np.array([], dtype=int);
    for i in range(len(x_train[it])):
        for j in range(len(x_train[it][i])):
            listt = np.append(listt, x_train[it][i][j]);
    #print(listt);
    X = np.append(X, listt);
    if(it == 1000): break;

#print(x_train);
#X = np.append(X, x_train);
#y = np.append(y, y_train);
X = X.reshape((-1, 784))
print(X);


X_tensor = torch.tensor(X, dtype=torch.float32).to(device)
y_tensor = torch.tensor(y, dtype=torch.float32).to(device)
print(X_tensor);
print(y_tensor);



mps
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0.0
0.16666666666666669
0.33333333333333337
0.5
0.6666666666666667
0.8333333333333334
1.0
1.1666666666666667
1.3333333333333335
1.5
1.6666666666666667
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='mps:0')
tensor([0., 1., 0.,  ..., 0., 1., 0.], device='mps:0')


In [83]:

# define the model
model = nn.Sequential(
    nn.Linear(784, 784),
    nn.ReLU(),
    #nn.Linear(784, 784),
    #nn.ReLU(),
    nn.Linear(784, 10),
    nn.Softmax()
)
model.to(device);
print(model)

# train the model
loss_fn   = nn.L1Loss()  # binary cross entropy
optimizer = optim.Adam(model.parameters(), lr=0.0000001)

n_epochs = 200
batch_size = 10

for epoch in range(n_epochs):
    for i in range(0, len(X_tensor), batch_size):
        if(i % 8000 == 0): 
            print(i / len(X_tensor) * 100, '% epoch', epoch);
            #for param in model.parameters():
            #    print(param.data)
        Xbatch = X_tensor[i:i+batch_size].to(device)
        #print(Xbatch.shape);
        y_pred = model(Xbatch).to(device);
        ybatch = y_tensor[i:i+batch_size].to(device);
        #print(y_pred);
        #print(y_tensor);
        #print("model.co: ", model.parameters());
        loss = loss_fn(y_pred, ybatch).to(device);
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(f'Finished epoch {epoch}, latest loss {loss}')

# compute accuracy (no_grad is optional)

Sequential(
  (0): Linear(in_features=784, out_features=784, bias=True)
  (1): ReLU()
  (2): Linear(in_features=784, out_features=10, bias=True)
  (3): Softmax(dim=None)
)
0.0 % epoch 0


/Users/tudor/Documents/Work AI/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py:1532: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
/Users/tudor/Documents/Work AI/.venv/lib/python3.9/site-packages/torch/nn/modules/loss.py:101: UserWarning: Using a target size (torch.Size([10])) that is different to the input size (torch.Size([10, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)


18.60421850654636 % epoch 0
37.20843701309272 % epoch 0
55.81265551963908 % epoch 0
74.41687402618544 % epoch 0
93.0210925327318 % epoch 0


/Users/tudor/Documents/Work AI/.venv/lib/python3.9/site-packages/torch/nn/modules/loss.py:101: UserWarning: Using a target size (torch.Size([10])) that is different to the input size (torch.Size([1, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)


Finished epoch 0, latest loss 0.001847937353886664
0.0 % epoch 1
18.60421850654636 % epoch 1
37.20843701309272 % epoch 1
55.81265551963908 % epoch 1
74.41687402618544 % epoch 1
93.0210925327318 % epoch 1
Finished epoch 1, latest loss 0.00415098387748003
0.0 % epoch 2
18.60421850654636 % epoch 2
37.20843701309272 % epoch 2
55.81265551963908 % epoch 2
74.41687402618544 % epoch 2
93.0210925327318 % epoch 2
Finished epoch 2, latest loss 0.006231661420315504
0.0 % epoch 3
18.60421850654636 % epoch 3
37.20843701309272 % epoch 3
55.81265551963908 % epoch 3
74.41687402618544 % epoch 3
93.0210925327318 % epoch 3
Finished epoch 3, latest loss 0.007036941591650248
0.0 % epoch 4
18.60421850654636 % epoch 4
37.20843701309272 % epoch 4
55.81265551963908 % epoch 4
74.41687402618544 % epoch 4
93.0210925327318 % epoch 4
Finished epoch 4, latest loss 0.007075078319758177
0.0 % epoch 5
18.60421850654636 % epoch 5
37.20843701309272 % epoch 5
55.81265551963908 % epoch 5
74.41687402618544 % epoch 5
93.02109

In [91]:
with torch.no_grad():
    y_pred = model(X_tensor).to(device);
    y_pred.to(device);
print(y_pred);
print(y_tensor)
accuracy = (y_pred.round() == y)
print(f"Accuracy {accuracy}")

tensor([[5.8710e-14, 8.7464e-22, 1.0000e+00,  ..., 7.2207e-09, 5.6907e-15,
         1.4306e-13],
        [0.0000e+00, 6.5417e-35, 2.8931e-05,  ..., 2.5550e-14, 1.0071e-36,
         5.7945e-05],
        [1.4719e-15, 9.7064e-09, 7.4457e-01,  ..., 4.3870e-05, 3.3133e-12,
         4.8131e-06],
        ...,
        [1.2664e-16, 2.5741e-22, 3.8489e-02,  ..., 2.6290e-17, 3.5789e-19,
         3.9493e-19],
        [5.6407e-23, 1.3060e-35, 1.0000e+00,  ..., 3.9357e-18, 2.1473e-12,
         3.9813e-20],
        [9.9990e-01, 4.9490e-23, 9.6676e-05,  ..., 6.1820e-10, 1.5474e-21,
         2.5885e-08]], device='mps:0')
tensor([0., 1., 0.,  ..., 0., 1., 0.], device='mps:0')
Accuracy False


In [86]:
test = pandas.read_csv("test1.csv");

arr = test.to_numpy();

print(arr);

X_test_tensor = torch.tensor(arr, dtype=torch.float32).to(device);

print(X_test_tensor);

print(model(X_test_tensor))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='mps:0')
tensor([[3.7517e-25, 1.0036e-32, 9.9488e-01,  ..., 8.3865e-11, 1.1995e-20,
         4.2392e-16],
        [6.0457e-29, 1.4544e-36, 8.8517e-14,  ..., 1.9249e-01, 2.4393e-23,
         8.0751e-01],
        [1.9380e-07, 1.6145e-12, 9.9964e-01,  ..., 4.9084e-10, 4.3536e-15,
         2.4130e-12],
        ...,
        [4.6195e-12, 7.6862e-24, 9.9521e-01,  ..., 2.9379e-22, 3.0791e-17,
         1.6773e-08],
        [9.8657e-24, 3.8779e-36, 1.0000e+00,  ..., 7.2419e-11, 1.7474e-08,
         3.8490e-16],
        [1.2974e-19, 3.1425e-25, 1.0000e+00,  ..., 4.8321e-12, 2.5669e-16,
         1.2865e-06]], device='mps:0'

/Users/tudor/Documents/Work AI/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py:1532: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


In [92]:
pandas.set_option('display.max_columns', None)

mat = model(X_test_tensor).cpu().data.numpy();
print(len(mat));

ans = pandas.DataFrame();

file = open("ansGPU.csv", 'w');

for i in range(len(mat)):
    mx = mat[i].argmax();
    file.write(str(i + 1) + ',' + str(mx) + "\n");
    #print("i: ", i, " mx:", mx)
    


/Users/tudor/Documents/Work AI/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py:1532: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


28000
